#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 17 15:11:15 2020

@author: gloiseau
"""

membrane = []
membraneWorked = []

with open('/exports/home/gloiseau/membranePdbs.txt', 'rt') as protfile:
#with open('/exports/home/gloiseau/pdbs_bitopic.txt', 'rt') as protfile:
    for line in protfile:
        membrane.append(line[:4])

with open('/exports/home/gloiseau/membranePdbsWorked_bc30_noredundancy.txt', 'rt') as protfile:
    for line in protfile:
        membraneWorked.append(line[:4])

newMem = []
F = open('memProteinList_cluster30.txt', 'w')
for i in range(len(membrane)):
    if membrane[i] in membraneWorked:
        #newMem.append(membrane[i])
        F.write(membrane[i])
        F.write('\n')
        
F.close()
        


